########### Image file ###########
FROM python:3.8.10-buster
##################################

########### update and install packages ###########
RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -y vim git && \
    rm -rf /var/lib/apt/lists*
###################################################

########### create workspace ###########
RUN mkdir /code
WORKDIR /code
ADD ./requirements.txt /code/
########################################

########### install packages via pip ###########
RUN pip install -r requirements.txt
RUN pip install pipenv
ADD . /code/
################################################